name: CI

on: [push]

jobs:
  build:

    runs-on: [windows]

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: Tests for OpenCV library
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
